version: "3.8"

services:
  sv-trivia:
    image: vicbrown2/sv-trivia:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/app/config # Path to your game config
    environment:
      - WEB_ORIGIN=http://trivia.stevenvince.com
      - SOCKET_URL=http://trivia.stevenvince.com
